name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: ng build --prod

      - name: Deploy to Hosting
        run: npm run deploy